server.port=8080
engine.path=src/main/resources/engine/pikafish-avx2.exe
engine.movetime.ms=400
engine.movetime.best.ms=200

# DeepSeek
deepseek.api.url=https://api.deepseek.com/v1/chat/completions
deepseek.api.key=${DEEPSEEK_API_KEY}

# =========================
# OpenAI Zero-shot (GPT-5-mini)
# =========================
openai.api.url=https://api.openai.com/v1/responses
openai.api.key=${OPENAI_API_KEY}
openai.api.model=gpt-5-mini
openai.reasoning.effort=minimal
openai.max_output_tokens=60

# =========================
# OpenAI CoT (GPT-5.2)
# =========================
openai.cot.api.url=https://api.openai.com/v1/responses
openai.cot.api.key=${OPENAI_API_KEY}
openai.cot.api.model=gpt-5.2
openai.cot.reasoning.effort=high
openai.cot.max_output_tokens=30000
openai.cot.reasoning.enable-summary=false

# =========================
# Gemini
# =========================
gemini.api.key=${GEMINI_API_KEY}
# Zero-shot
gemini.model.zeroshot=gemini-2.5-flash
# CoT Gemini 3 Pro
gemini.model.cot=gemini-2.5-pro

